[package]
name = "ufwprofile"
version = "0.1.0"
edition = "2021"
description = "UFW app profile written in pure rust"
authors = ["Sandipsinh Rathod"]
readme = "README.md"
categories = [""]
license = "MIT"
repository = "https://github.com/ssddOnTop/rust-ufw-app-profile"
homepage = "https://www.ssdd.dev/rustufwapp-profile"
keywords = ["UFW profile"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
